import "./globals.css";
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import Providers from "./Global/Redux/providers";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>{children}</body>
    </html>
  );
}
